### ISSUE TITLE
[Bug] Integration not working with TrueNAS running in VM

### ISSUE THREAD

**Issue by Pure1gamer** [tomaae/homeassistant-truenas#9]
Seems that the intergration isn't able to get data from Truenas. Have made multiple attempts with multiple API keys and doesn't seem to fetch the data from the application

Version
core-2022.3.7
supervisor-2022.03.5
TrueNAS v1.0.1

TrueNAS (IP) unable to fetch data (500)
TrueNAS (IP) unable to fetch data (401)
TrueNAS (IP) unable to fetch data (no_respose)
TrueNAS (IP) unable to fetch data (no_respose)
TrueNAS (IP) unable to fetch data (no_respose)

**Comment by tomaae** [comment]
What is your truenas version?
Are those errors from integration setup, or after?

**Comment by Pure1gamer** [comment]
Truenas: TrueNAS-12.0-U8

That's after the integration setup :)

**Comment by tomaae** [comment]
I have the same.
Can you send me integration debugs?

**Comment by Pure1gamer** [comment]
Yeah for sure - https://pastebin.com/1hNb9WPa

Let me know if you need anything else!

**Comment by tomaae** [comment]
hmm, so it can connect, but randomly gets error from api or cant reach it at all. it is not a problem with API key.
looks like something weird with networking, could even be a firewall or some kind of connection limiter.

here we can see it got correct response. but missing hostname is weird, can you check if that is true?
```
2022-03-27 21:11:09 DEBUG (SyncWorker_24) [custom_components.truenas.truenas_api] TrueNAS query: system/info, get, {}
2022-03-27 21:11:10 DEBUG (SyncWorker_24) [custom_components.truenas.truenas_api] TrueNAS query response: {'version': 'TrueNAS-12.0-U8', 'buildtime': {'$date': 1643730318000}, 'hostname': '', 'physmem': 8538009600, 'model': 'Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz', 'cores': 2, 'loadavg': [0.703125, 0.67333984375, 0.33349609375], 'uptime': '0:03:46.235041', 'uptime_seconds': 226.235040674, 'system_serial': 'VMware-56 4d 91 58 6f 05 e1 ac-88 6c 41 05 1a af cb 28', 'system_product': 'VMware Virtual Platform', 'system_product_version': 'None', 'license': None, 'boottime': {'$date': 1648375643000}, 'datetime': {'$date': 1648375869998}, 'birthday': {'$date': 1648287622424}, 'timezone': 'America/Los_Angeles', 'system_manufacturer': 'VMware, Inc.', 'ecc_memory': False}
```
It would be also good idea to check if vmware cpu and network is not overloaded. No idea how truenas api reacts in such a state.

Those http error codes are coming directly from api:
401 Unauthorized
500 Internal Server Error (on truenas side)

Can you give me more info about your vmware setup? I was doing development and testing on truenas installed directly on server hardware. I can try to setup a virtualized envinroment to see how it behaves.

also, you dont have to use pastebin. you can paste it here and encluse in tripple back quotes and it will format nicely. 

out of my couriosity, how did you found out about this integration? since it is still awaiting approval for HACS, I didnt even annouced it yet.

**Comment by tomaae** [comment]
I was testing scale in VM and I think you have same problem.
CPU temperature graph query crashes when truenas is running on VM, at least for scale, which results in code 500.
This is bug on truenas side, so I added a workaround. Its not like temperature sensor makes sense on VM anyway.
Give it a try and let me know :)

**Comment by pcampan** [comment]
I think I have a very similar configuration Proxmox with TrueNAS Scale and get Unknown for all entities after a Proxmox restart.

```
2022-04-11 08:58:06 DEBUG (SyncWorker_4) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.101 query: reporting/get_data, post, {'graphs': [{'name': 'load'}, {'name': 'cputemp'}, {'name': 'cpu'}, {'name': 'arcsize'}, {'name': 'arcratio'}], 'reporting_query': {'start': 'now-90s', 'end': 'now-30s', 'aggregate': True}}
2022-04-11 08:58:07 WARNING (SyncWorker_4) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.101 unable to fetch data (500)
```

**Comment by tomaae** [comment]
> I think I have a very similar configuration Proxmox with TrueNAS Scale and get Unknown for all entities after a Proxmox restart.
> 
> TrueNAS-SCALE-22.02.0.1 installation_type Home Assistant OS version": "2022.4.2 "truenas": "version": "1.0.1",
> 
> ```
> 2022-04-11 09:36:06 DEBUG (SyncWorker_9) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.100 query: system/info, get, {}
> 2022-04-11 09:36:06 DEBUG (SyncWorker_9) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.100 query response: {'version': 'TrueNAS-SCALE-22.02.0.1', 'buildtime': {'$date': 1647930354000}, 'hostname': 'PCC-NAS1.localhost', 'physmem': 12553285632, 'model': 'Intel Core Processor (Skylake)', 'cores': 2, 'physical_cores': 2, 'loadavg': [0.02, 0.06, 0.13], 'uptime': '11:28:08.612310', 'uptime_seconds': 41288.612310437, 'system_serial': 'Not Specified', 'system_product': 'Standard PC (i440FX + PIIX, 1996)', 'system_product_version': 'pc-i440fx-6.1', 'license': None, 'boottime': {'$date': 1649642878281}, 'datetime': {'$date': 1649684166893}, 'birthday': None, 'timezone': 'America/Toronto', 'system_manufacturer': 'QEMU', 'ecc_memory': True}
> 2022-04-11 09:36:06 DEBUG (SyncWorker_9) [custom_components.truenas.apiparser] Processing source [{'version': 'TrueNAS-SCALE-22.02.0.1', 'buildtime': {'$date': 1647930354000}, 'hostname': 'PCC-NAS1.localhost', 'physmem': 12553285632, 'model': 'Intel Core Processor (Skylake)', 'cores': 2, 'physical_cores': 2, 'loadavg': [0.02, 0.06, 0.13], 'uptime': '11:28:08.612310', 'uptime_seconds': 41288.612310437, 'system_serial': '**REDACTED**', 'system_product': 'Standard PC (i440FX + PIIX, 1996)', 'system_product_version': 'pc-i440fx-6.1', 'license': None, 'boottime': {'$date': 1649642878281}, 'datetime': {'$date': 1649684166893}, 'birthday': None, 'timezone': 'America/Toronto', 'system_manufacturer': 'QEMU', 'ecc_memory': True}]
> 2022-04-11 09:36:06 DEBUG (SyncWorker_9) [custom_components.truenas.apiparser] Processing entry {'version': 'TrueNAS-SCALE-22.02.0.1', 'buildtime': {'$date': 1647930354000}, 'hostname': 'PCC-NAS1.localhost', 'physmem': 12553285632, 'model': 'Intel Core Processor (Skylake)', 'cores': 2, 'physical_cores': 2, 'loadavg': [0.02, 0.06, 0.13], 'uptime': '11:28:08.612310', 'uptime_seconds': 41288.612310437, 'system_serial': '**REDACTED**', 'system_product': 'Standard PC (i440FX + PIIX, 1996)', 'system_product_version': 'pc-i440fx-6.1', 'license': None, 'boottime': {'$date': 1649642878281}, 'datetime': {'$date': 1649684166893}, 'birthday': None, 'timezone': 'America/Toronto', 'system_manufacturer': 'QEMU', 'ecc_memory': True}
> 2022-04-11 09:36:06 DEBUG (SyncWorker_0) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.100 query: reporting/get_data, post, {'graphs': [{'name': 'load'}, {'name': 'cputemp'}, {'name': 'cpu'}, {'name': 'arcsize'}, {'name': 'arcratio'}], 'reporting_query': {'start': 'now-90s', 'end': 'now-30s', 'aggregate': True}}
> 2022-04-11 09:36:07 WARNING (SyncWorker_0) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.100 unable to fetch data (500)
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_uptime
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_cpu_temperature
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_load_shortterm
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_load_midterm
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_load_longterm
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_cpu_usage
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_cache_size-arc_value
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_cache_size-L2_value
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_cache_ratio-arc_value
> 2022-04-11 09:36:07 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS_1-system_cache_ratio-L2_value
> ```

Thanks, try with master. It should work now.

**Comment by pcampan** [comment]
Thanks for the quick response.  I'm not sure what the master is, I am using HACS to manage the integration.  I did find there was a 1.0.2 version of the integration, but I'm still getting the same 500 error.

**Comment by tomaae** [comment]
In HACS, you can choose to install master in version selection. Thats the most easy and preferred  method.

**Comment by pcampan** [comment]
Thanks for that bit of advice about HACS, was always just picking the version that came up in the dialogue.

The integration is picking up the data as you suggested.

I need to check my other integrations are using master as well.

**Comment by pcampan** [comment]
ok, I will only use another branch based on author's advice.

strange I have 2 TrueNAS Scale servers on different Proxmox servers.  1 is reporting correctly in HA and one I'm still getting a 500.

```
2022-04-11 11:24:07 DEBUG (SyncWorker_5) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.101 query: system/info, get, {}
2022-04-11 11:24:07 DEBUG (SyncWorker_5) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.101 query response: {'version': 'TrueNAS-SCALE-22.02.0.1', 'buildtime': {'$date': 1647930354000}, 'hostname': 'PCC-NAS2.localhost', 'physmem': 12552777728, 'model': 'AMD Phenom(tm) 9550 Quad-Core Processor', 'cores': 4, 'physical_cores': 4, 'loadavg': [0.04, 0.1, 0.04], 'uptime': '2:44:00.515940', 'uptime_seconds': 9840.515940204, 'system_serial': 'Not Specified', 'system_product': 'Standard PC (i440FX + PIIX, 1996)', 'system_product_version': 'pc-i440fx-6.1', 'license': None, 'boottime': {'$date': 1649680807088}, 'datetime': {'$date': 1649690647604}, 'birthday': None, 'timezone': 'America/Toronto', 'system_manufacturer': 'QEMU', 'ecc_memory': True}
2022-04-11 11:24:07 DEBUG (SyncWorker_5) [custom_components.truenas.apiparser] Processing source [{'version': 'TrueNAS-SCALE-22.02.0.1', 'buildtime': {'$date': 1647930354000}, 'hostname': 'PCC-NAS2.localhost', 'physmem': 12552777728, 'model': 'AMD Phenom(tm) 9550 Quad-Core Processor', 'cores': 4, 'physical_cores': 4, 'loadavg': [0.04, 0.1, 0.04], 'uptime': '2:44:00.515940', 'uptime_seconds': 9840.515940204, 'system_serial': '**REDACTED**', 'system_product': 'Standard PC (i440FX + PIIX, 1996)', 'system_product_version': 'pc-i440fx-6.1', 'license': None, 'boottime': {'$date': 1649680807088}, 'datetime': {'$date': 1649690647604}, 'birthday': None, 'timezone': 'America/Toronto', 'system_manufacturer': 'QEMU', 'ecc_memory': True}]
2022-04-11 11:24:07 DEBUG (SyncWorker_5) [custom_components.truenas.apiparser] Processing entry {'version': 'TrueNAS-SCALE-22.02.0.1', 'buildtime': {'$date': 1647930354000}, 'hostname': 'PCC-NAS2.localhost', 'physmem': 12552777728, 'model': 'AMD Phenom(tm) 9550 Quad-Core Processor', 'cores': 4, 'physical_cores': 4, 'loadavg': [0.04, 0.1, 0.04], 'uptime': '2:44:00.515940', 'uptime_seconds': 9840.515940204, 'system_serial': '**REDACTED**', 'system_product': 'Standard PC (i440FX + PIIX, 1996)', 'system_product_version': 'pc-i440fx-6.1', 'license': None, 'boottime': {'$date': 1649680807088}, 'datetime': {'$date': 1649690647604}, 'birthday': None, 'timezone': 'America/Toronto', 'system_manufacturer': 'QEMU', 'ecc_memory': True}
2022-04-11 11:24:08 DEBUG (SyncWorker_6) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.101 query: reporting/get_data, post, {'graphs': [{'name': 'load'}, {'name': 'cpu'}, {'name': 'arcsize'}, {'name': 'arcratio'}], 'reporting_query': {'start': 'now-90s', 'end': 'now-30s', 'aggregate': True}}
2022-04-11 11:24:08 WARNING (SyncWorker_6) [custom_components.truenas.truenas_api] TrueNAS 192.168.1.101 unable to fetch data (500)

```

**Comment by pcampan** [comment]
You're probably right, on the dashboard there is an error with getting the network graph.  I also see on the second server some of the graphs aren't collecting information.  

The issue seems to be mine.

**Comment by tomaae** [comment]
even network? interesting.
let me know if you figure out what the issue was

**Comment by tomaae** [comment]
Confirmed this error 500 behaviour like a bug by ixsystems. Jira ticked opened [NAS-115761](https://jira.ixsystems.com/browse/NAS-115761)

**Comment by mokshmridul** [comment]
Hi,

Im running Truenas Core in a Proxmox VM, and HA in its own VM. However i am unable to get the data via the integration. I even tried installing the master branch as suggested above, but to no avail. My diagnostics file is attached here.

**Comment by tomaae** [comment]
> Hi,
> 
> Im running Truenas Core in a Proxmox VM, and HA in its own VM. However i am unable to get the data via the integration. I even tried installing the master branch as suggested above, but to no avail. My diagnostics file is attached here. [config_entry-truenas-3d54f12450d2bfe3057f2f9a52e3fc38.json.txt](https://github.com/tomaae/homeassistant-truenas/files/8552065/config_entry-truenas-3d54f12450d2bfe3057f2f9a52e3fc38.json.txt)

diagnostics wont help here. you will need to debug it to see where it fails.

**Comment by mokshmridul** [comment]
> > Hi,
> > Im running Truenas Core in a Proxmox VM, and HA in its own VM. However i am unable to get the data via the integration. I even tried installing the master branch as suggested above, but to no avail. My diagnostics file is attached here. [config_entry-truenas-3d54f12450d2bfe3057f2f9a52e3fc38.json.txt](https://github.com/tomaae/homeassistant-truenas/files/8552065/config_entry-truenas-3d54f12450d2bfe3057f2f9a52e3fc38.json.txt)
> 
> diagnostics wont help here. you will need to debug it to see where it fails.

Sure, this is what my logs say 

`2022-04-25 12:35:37 DEBUG (SyncWorker_21) [custom_components.truenas.truenas_api] TrueNAS 192.168.0.10 query: system/info, get, {}
2022-04-25 12:35:37 DEBUG (SyncWorker_21) [custom_components.truenas.truenas_api] TrueNAS 192.168.0.10 query response: {'version': 'TrueNAS-12.0-U8', 'buildtime': {'$date': 1643778918000}, 'hostname': 'truenas.mokshmridul', 'physmem': 137365667840, 'model': 'AMD EPYC-Rome Processor', 'cores': 16, 'loadavg': [0.10791015625, 0.13623046875, 0.15283203125], 'uptime': '2 days, 0:53:31.540590', 'uptime_seconds': 176011.540590421, 'system_serial': 'Not Specified', 'system_product': 'Standard PC (Q35 + ICH9, 2009)', 'system_product_version': 'pc-q35-6.2', 'license': None, 'boottime': {'$date': 1650694325000}, 'datetime': {'$date': 1650870337150}, 'birthday': {'$date': 1607957856005}, 'timezone': 'Asia/Kolkata', 'system_manufacturer': 'QEMU', 'ecc_memory': True}
2022-04-25 12:35:37 DEBUG (SyncWorker_21) [custom_components.truenas.apiparser] Processing source [{'version': 'TrueNAS-12.0-U8', 'buildtime': {'$date': 1643778918000}, 'hostname': 'truenas.mokshmridul', 'physmem': 137365667840, 'model': 'AMD EPYC-Rome Processor', 'cores': 16, 'loadavg': [0.10791015625, 0.13623046875, 0.15283203125], 'uptime': '2 days, 0:53:31.540590', 'uptime_seconds': 176011.540590421, 'system_serial': '**REDACTED**', 'system_product': 'Standard PC (Q35 + ICH9, 2009)', 'system_product_version': 'pc-q35-6.2', 'license': None, 'boottime': {'$date': 1650694325000}, 'datetime': {'$date': 1650870337150}, 'birthday': {'$date': 1607957856005}, 'timezone': 'Asia/Kolkata', 'system_manufacturer': 'QEMU', 'ecc_memory': True}]
2022-04-25 12:35:37 DEBUG (SyncWorker_21) [custom_components.truenas.apiparser] Processing entry {'version': 'TrueNAS-12.0-U8', 'buildtime': {'$date': 1643778918000}, 'hostname': 'truenas.mokshmridul', 'physmem': 137365667840, 'model': 'AMD EPYC-Rome Processor', 'cores': 16, 'loadavg': [0.10791015625, 0.13623046875, 0.15283203125], 'uptime': '2 days, 0:53:31.540590', 'uptime_seconds': 176011.540590421, 'system_serial': '**REDACTED**', 'system_product': 'Standard PC (Q35 + ICH9, 2009)', 'system_product_version': 'pc-q35-6.2', 'license': None, 'boottime': {'$date': 1650694325000}, 'datetime': {'$date': 1650870337150}, 'birthday': {'$date': 1607957856005}, 'timezone': 'Asia/Kolkata', 'system_manufacturer': 'QEMU', 'ecc_memory': True}
2022-04-25 12:35:37 DEBUG (SyncWorker_19) [custom_components.truenas.truenas_api] TrueNAS 192.168.0.10 query: reporting/get_data, post, {'graphs': [{'name': 'load'}, {'name': 'cputemp'}, {'name': 'cpu'}, {'name': 'arcsize'}, {'name': 'arcratio'}], 'reporting_query': {'start': 'now-90s', 'end': 'now-30s', 'aggregate': True}}
2022-04-25 12:35:37 WARNING (SyncWorker_19) [custom_components.truenas.truenas_api] TrueNAS 192.168.0.10 unable to fetch data (500)
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_uptime
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_cpu_temperature
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_load_shortterm
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_load_midterm
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_load_longterm
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_cpu_usage
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_cache_size-arc_value
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_cache_size-L2_value
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_cache_ratio-arc_value
2022-04-25 12:35:37 DEBUG (MainThread) [custom_components.truenas.model] Updating entity TrueNAS-system_cache_ratio-L2_value`

**Comment by tomaae** [comment]
This is not master branch, you need to use it for proxmox until next release.

**Comment by mokshmridul** [comment]
> This is not master branch, you need to use it for proxmox until next release.

I'm sorry, i did not understand. 

I got the "master branch" via HACS. Have i done something wrong, and what does it have to do with Proxmox?

**Comment by tomaae** [comment]
not sure, try to remove it and install the integration again

**Comment by mokshmridul** [comment]
> not sure, try to remove it and install the integration again

That seems to have fixed the issue. Thanks.

**Comment by tomaae** [comment]
I will be closing this one as we have workaround. #12 stays open until TrueNAS fixes the bug
